### ISSUE TITLE
Add this list to sindresorhus/awesome

### ISSUE THREAD

**Issue by greensn0w** [aharris88/awesome-cli-apps#7]
You should add this list to [**_sindresorhus/awesome_**](https://github.com/sindresorhus/awesome), so more people can find it :+1:

**Comment by aharris88** [comment]
I added a pull request: https://github.com/sindresorhus/awesome/pull/379

**Comment by aharris88** [comment]
I closed the pull request until this list is really awesome. This is what I think we should do before adding it to [_sindresorhus/awesome_](https://github.com/sindresorhus/awesome).

- [] Add a license
- [] Make sure all apps are awesome
- [] Organize better (#14)
- [] Make sure this list is distinguished from https://github.com/alebcay/awesome-shell
- [] Add a link at the bottom to more awesome lists
